# Generated by Django 5.2.5 on 2025-09-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Blocked IP address')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address tracked')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time address was tracked')),
                ('path', models.CharField(max_length=500, verbose_name='Path accessed by the IP')),
                ('country', models.CharField(max_length=200, verbose_name='Country of the IP')),
                ('city', models.CharField(max_length=250, verbose_name='City of the IP')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Suspicious IP address')),
                ('reason', models.CharField(max_length=200, verbose_name='Reason flagged')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-flagged_at'],
            },
        ),
    ]
