# Generated by Django 5.2.5 on 2025-09-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='A blocked IP address')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address tracked')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time address was tracked')),
                ('path', models.CharField(verbose_name='the path accessed by the IP')),
                ('country', models.CharField(max_length=200, verbose_name='Country of the IP')),
                ('city', models.CharField(max_length=250, verbose_name='City of the IP')),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
    ]
